CREATE OR REPLACE SCHEMA OUTLIERS;

CREATE OR REPLACE TABLE OUTLIERS.MEMBER_MONTHS AS
SELECT
  MM.PERSON_ID,
  MM.MEMBER_ID,
  SUBSTR(MM.YEAR_MONTH, 1, 4) AS YEAR,
  MM.YEAR_MONTH,
  PT.SEX,
  PT.RACE,
  PT.STATE,
  PT.AGE,
  PT.AGE_GROUP,
  RSK.PAYMENT_YEAR,
  RSK.V24_RISK_SCORE,
  RSK.V24_RISK_SCORE / AVG.ANNUAL_AVG_RISK_SCORE AS POPULATION_NORMALIZED_RISK_SCORE
FROM CORE.MEMBER_MONTHS MM
LEFT JOIN CORE.PATIENT PT ON MM.PERSON_ID = PT.PERSON_ID
LEFT JOIN CMS_HCC.PATIENT_RISK_SCORES RSK ON MM.PERSON_ID = RSK.PERSON_ID
LEFT JOIN (
  SELECT PAYMENT_YEAR, AVG(V24_RISK_SCORE) AS ANNUAL_AVG_RISK_SCORE
  FROM CMS_HCC.PATIENT_RISK_SCORES_MONTHLY
  GROUP BY PAYMENT_YEAR
) AVG ON RSK.PAYMENT_YEAR = AVG.PAYMENT_YEAR
ORDER BY MEMBER_ID;

CREATE OR REPLACE VIEW OUTLIERS.MEDICAL_CLAIMS AS
SELECT
  CLM.CLAIM_ID,
  CLM.CLAIM_LINE_NUMBER,
  CLM.CLAIM_TYPE,
  CLM.PERSON_ID,
  CLM.MEMBER_ID,
  CLM.CLAIM_START_DATE AS INCR_DATE,
  CLM.PAID_DATE,
  TO_CHAR(CLM.CLAIM_START_DATE, 'YYYYMM') AS INCR_MONTH,
  TO_CHAR(CLM.PAID_DATE, 'YYYYMM') AS PAID_MONTH,
  TO_CHAR(CLM.CLAIM_START_DATE, 'YYYY') AS INCR_YEAR,
  TO_CHAR(CLM.PAID_DATE, 'YYYY') AS PAID_YEAR,
  CCSR.NORMALIZED_CODE AS DX_CODE,
  CCSR.CODE_DESCRIPTION AS DX_DESCRIPTION,
  CCSR.BODY_SYSTEM AS DX_CCSR_CATEGORY1,
  CCSR.CCSR_CATEGORY_DESCRIPTION AS DX_CCSR_CATEGORY2,
  CLM.ENCOUNTER_ID,
  CLM.ENCOUNTER_TYPE,
  CLM.ENCOUNTER_GROUP,
  CLM.SERVICE_CATEGORY_1,
  CLM.SERVICE_CATEGORY_2,
  CLM.SERVICE_CATEGORY_3,
  CASE WHEN CLM.DRG_CODE_TYPE = 'ms-drg' THEN CLM.DRG_CODE END AS MS_DRG_CODE,
  CASE WHEN CLM.DRG_CODE_TYPE = 'ms-drg' THEN CLM.DRG_DESCRIPTION END AS MS_DRG_DESCRIPTION,
  CASE WHEN CLM.DRG_CODE_TYPE = 'apr-drg' THEN CLM.DRG_CODE END AS APR_DRG_CODE,
  CASE WHEN CLM.DRG_CODE_TYPE = 'apr-drg' THEN CLM.DRG_DESCRIPTION END AS APR_DRG_DESCRIPTION,
  CLM.REVENUE_CENTER_CODE,
  CLM.REVENUE_CENTER_DESCRIPTION,
  CLM.HCPCS_CODE,
  RBCS_CAT_DESC,
  RBCS_SUBCAT_DESC,
  RBCS_FAMILY_DESC,
  CLM.PAID_AMOUNT,
  CLM.RENDERING_ID
FROM CORE.MEDICAL_CLAIM CLM
LEFT JOIN CCSR.LONG_CONDITION_CATEGORY CCSR
  ON CLM.CLAIM_ID = CCSR.CLAIM_ID
  AND CLM.PERSON_ID = CCSR.PERSON_ID
LEFT JOIN TERMINOLOGY.HCPCS_TO_RBCS RBCS
  ON CLM.HCPCS_CODE = RBCS.HCPCS_CD
  AND RBCS.CURRENT_FLAG = 1
WHERE CCSR.CONDITION_RANK=1 AND CCSR.CCSR_CATEGORY_RANK=1;

CREATE OR REPLACE VIEW OUTLIERS.RX_CLAIMS AS
SELECT
  RX.CLAIM_ID,
  RX.CLAIM_LINE_NUMBER,
  'PHARMACY' AS CLAIM_TYPE,
  RX.PERSON_ID,
  RX.MEMBER_ID,
  RX.DISPENSING_DATE AS INCR_DATE,
  RX.PAID_DATE,
  TO_CHAR(RX.DISPENSING_DATE, 'YYYYMM') AS INCR_MONTH,
  TO_CHAR(RX.PAID_DATE, 'YYYYMM') AS PAID_MONTH,
  TO_CHAR(RX.DISPENSING_DATE, 'YYYY') AS INCR_YEAR,
  TO_CHAR(RX.PAID_DATE, 'YYYY') AS PAID_YEAR,
  RX.NDC_CODE,
  RX.NDC_DESCRIPTION,
  RX.QUANTITY,
  RX.DAYS_SUPPLY,
  RX.REFILLS,
  RX.PAID_AMOUNT,
  RX.PRESCRIBING_PROVIDER_ID AS PRESCRIBER_NPI,
  RX.DISPENSING_PROVIDER_ID AS DISPENSING_NPI,
  RX2.RXCUI AS RX_NORM_CODE,
  ATC.RXNORM_DESCRIPTION AS RXNORM_DESCRIPTION,
  ATC.ATC_1_CODE,
  ATC.ATC_1_NAME,
  ATC.ATC_2_CODE,
  ATC.ATC_2_NAME,
  ATC.ATC_3_CODE,
  ATC.ATC_3_NAME,
  ATC.ATC_4_CODE,
  ATC.ATC_4_NAME
FROM CORE.PHARMACY_CLAIM RX
LEFT JOIN PHARMACY.PHARMACY_CLAIM_EXPANDED RX2
  ON RX.CLAIM_ID = RX2.CLAIM_ID
  AND RX.CLAIM_LINE_NUMBER = RX2.CLAIM_LINE_NUMBER
LEFT JOIN TERMINOLOGY.RXNORM_TO_ATC ATC
  ON RX2.RXCUI = ATC.RXCUI;

CREATE OR REPLACE VIEW OUTLIERS.ALL_CLAIMS AS 
SELECT 
    CLAIM_ID
    , CLAIM_LINE_NUMBER
    , CLAIM_TYPE
    , PERSON_ID
    , MEMBER_ID
    , INCR_DATE
    , PAID_DATE
    , INCR_MONTH
    , PAID_MONTH
    , INCR_YEAR
    , PAID_YEAR
    , PAID_AMOUNT
    , DX_CODE
    , DX_DESCRIPTION
    , DX_CCSR_CATEGORY1
    , DX_CCSR_CATEGORY2
    , ENCOUNTER_ID
    , ENCOUNTER_TYPE
    , ENCOUNTER_GROUP
    , SERVICE_CATEGORY_1
    , SERVICE_CATEGORY_2
    , SERVICE_CATEGORY_3
    , MS_DRG_CODE
    , MS_DRG_DESCRIPTION
    , APR_DRG_CODE
    , APR_DRG_DESCRIPTION
    , REVENUE_CENTER_CODE
    , REVENUE_CENTER_DESCRIPTION
    , HCPCS_CODE
    , RBCS_CAT_DESC
    , RBCS_SUBCAT_DESC
    , RBCS_FAMILY_DESC
    , RENDERING_ID
    , NULL AS NDC_CODE
    , NULL AS NDC_DESCRIPTION
    , NULL AS QUANTITY
    , NULL AS DAYS_SUPPLY
    , NULL AS REFILLS
    , NULL AS PRESCRIBER_NPI
    , NULL AS DISPENSING_NPI
    , NULL AS RX_NORM_CODE
    , NULL AS RXNORM_DESCRIPTION
    , NULL AS ATC_1_CODE
    , NULL AS ATC_1_NAME
    , NULL AS ATC_2_CODE
    , NULL AS ATC_2_NAME
    , NULL AS ATC_3_CODE
    , NULL AS ATC_3_NAME
    , NULL AS ATC_4_CODE
    , NULL AS ATC_4_NAME
FROM OUTLIERS.MEDICAL_CLAIMS
UNION ALL 
SELECT 
    CLAIM_ID
    , CLAIM_LINE_NUMBER
    , CLAIM_TYPE
    , PERSON_ID
    , MEMBER_ID
    , INCR_DATE
    , PAID_DATE
    , INCR_MONTH
    , PAID_MONTH
    , INCR_YEAR
    , PAID_YEAR
    , PAID_AMOUNT
    , NULL AS DX_CODE
    , NULL AS DX_DESCRIPTION
    , NULL AS DX_CCSR_CATEGORY1
    , NULL AS DX_CCSR_CATEGORY2
    , NULL AS ENCOUNTER_ID
    , NULL AS ENCOUNTER_TYPE
    , NULL AS ENCOUNTER_GROUP
    , NULL AS SERVICE_CATEGORY_1
    , NULL AS SERVICE_CATEGORY_2
    , NULL AS SERVICE_CATEGORY_3
    , NULL AS MS_DRG_CODE
    , NULL AS MS_DRG_DESCRIPTION
    , NULL AS APR_DRG_CODE
    , NULL AS APR_DRG_DESCRIPTION
    , NULL AS REVENUE_CENTER_CODE
    , NULL AS REVENUE_CENTER_DESCRIPTION
    , NULL AS HCPCS_CODE
    , NULL AS RBCS_CAT_DESC
    , NULL AS RBCS_SUBCAT_DESC
    , NULL AS RBCS_FAMILY_DESC
    , NULL AS RENDERING_ID
    , NDC_CODE
    , NDC_DESCRIPTION
    , QUANTITY
    , DAYS_SUPPLY
    , REFILLS
    , PRESCRIBER_NPI
    , DISPENSING_NPI
    , RX_NORM_CODE
    , RXNORM_DESCRIPTION
    , ATC_1_CODE
    , ATC_1_NAME
    , ATC_2_CODE
    , ATC_2_NAME
    , ATC_3_CODE
    , ATC_3_NAME
    , ATC_4_CODE
    , ATC_4_NAME
FROM OUTLIERS.RX_CLAIMS;

CREATE OR REPLACE TABLE OUTLIERS.ALL_CLAIMS_AGG AS
SELECT
  CLAIM_TYPE,
  MEMBER_ID,
  INCR_MONTH,
  INCR_YEAR,
  DX_CODE,
  DX_DESCRIPTION,
  DX_CCSR_CATEGORY1,
  DX_CCSR_CATEGORY2,
  ENCOUNTER_ID,
  ENCOUNTER_TYPE,
  ENCOUNTER_GROUP,
  SERVICE_CATEGORY_1,
  SERVICE_CATEGORY_2,
  SERVICE_CATEGORY_3,
  MS_DRG_CODE,
  MS_DRG_DESCRIPTION,
  APR_DRG_CODE,
  APR_DRG_DESCRIPTION,
  REVENUE_CENTER_CODE,
  REVENUE_CENTER_DESCRIPTION,
  HCPCS_CODE,
  RBCS_CAT_DESC,
  RBCS_SUBCAT_DESC,
  RBCS_FAMILY_DESC,
  SUM(PAID_AMOUNT) AS PAID_AMOUNT
FROM OUTLIERS.ALL_CLAIMS
GROUP BY
  CLAIM_TYPE,
  MEMBER_ID,
  INCR_MONTH,
  INCR_YEAR,
  DX_CODE,
  DX_DESCRIPTION,
  DX_CCSR_CATEGORY1,
  DX_CCSR_CATEGORY2,
  ENCOUNTER_ID,
  ENCOUNTER_TYPE,
  ENCOUNTER_GROUP,
  SERVICE_CATEGORY_1,
  SERVICE_CATEGORY_2,
  SERVICE_CATEGORY_3,
  MS_DRG_CODE,
  MS_DRG_DESCRIPTION,
  APR_DRG_CODE,
  APR_DRG_DESCRIPTION,
  REVENUE_CENTER_CODE,
  REVENUE_CENTER_DESCRIPTION,
  HCPCS_CODE,
  RBCS_CAT_DESC,
  RBCS_SUBCAT_DESC,
  RBCS_FAMILY_DESC;

CREATE OR REPLACE VIEW OUTLIERS.OUTLIER_MEMBERS AS
WITH member_paid_by_year AS (
  SELECT MEMBER_ID, INCR_YEAR, SUM(PAID_AMOUNT) AS PAID
  FROM OUTLIERS.ALL_CLAIMS_AGG
  GROUP BY MEMBER_ID, INCR_YEAR
),
stats_by_year AS (
  SELECT
    INCR_YEAR,
    SUM(PAID)        AS TOTAL_PAID,
    AVG(PAID)        AS MEAN_PAID,
    STDDEV(PAID)     AS STDDEV_PAID,
    COUNT(DISTINCT MEMBER_ID) AS TOTAL_MEMBERS
  FROM member_paid_by_year
  GROUP BY INCR_YEAR
)
SELECT
  mpby.MEMBER_ID,
  mpby.INCR_YEAR,
  mpby.PAID,
  sby.TOTAL_MEMBERS,
  sby.MEAN_PAID,
  (sby.MEAN_PAID + 2 * sby.STDDEV_PAID) AS OUTLIER_THRESHOLD,
  mpby.PAID / TOTAL_PAID       AS PERCENT_PAID,
  CASE
    WHEN mpby.PAID > (sby.MEAN_PAID + 2 * sby.STDDEV_PAID) THEN 'OUTLIER'
    ELSE 'NORMAL'
  END AS OUTLIER_FLAG
FROM member_paid_by_year mpby
LEFT JOIN stats_by_year sby ON mpby.INCR_YEAR = sby.INCR_YEAR
ORDER BY mpby.PAID DESC;

CREATE OR REPLACE TABLE OUTLIERS.OUTLIER_CLAIMS_AGG AS
SELECT
  aca.*,
  om.MEAN_PAID,
  om.TOTAL_MEMBERS
FROM OUTLIERS.ALL_CLAIMS_AGG aca
INNER JOIN OUTLIERS.OUTLIER_MEMBERS om
  ON aca.MEMBER_ID = om.MEMBER_ID
  AND aca.INCR_YEAR = om.INCR_YEAR
WHERE EXISTS (
    SELECT 1 
    FROM OUTLIERS.OUTLIER_MEMBERS om
    WHERE om.OUTLIER_FLAG = 'OUTLIER'
      AND om.MEMBER_ID = aca.MEMBER_ID
);

CREATE OR REPLACE TABLE OUTLIERS.OUTLIER_MEMBER_MONTHS AS
SELECT *
FROM OUTLIERS.MEMBER_MONTHS
WHERE MEMBER_ID IN(
    SELECT DISTINCT MEMBER_ID
    FROM OUTLIERS.OUTLIER_MEMBERS
    WHERE OUTLIER_FLAG = 'OUTLIER'
);